[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title =  "ORBIT Contrib Assets"
description="Extension containing configuration instances of different assets and sensors contributed by external developers"
readme  = ""
repository = "https://github.com/alvarobelmontebaeza/orbit"
category = "robotics"
keywords = ["kit", "robotics", "assets", "orbit"]

[dependencies]
"omni.isaac.orbit" = {}

# Main python module this extension provides.
[[python.module]]
name = "omni.isaac.contrib_assets"
